export const UPDATE_CURRENT_RATE_ACTION = 'UPDATE_CURRENT_RATE';
export const ADD_TO_CURRENT_LIST_ACTION = 'ADD_TO_CURRENT_LIST';
export const UPDATE_REFRESH_RATE_ACTION = 'UPDATE_REFRESH_RATE';
export const UPDATE_SOURCE_CURRENCY_ACTION = 'UPDATE_SOURCE_CURRENCY';
export const UPDATE_HISTORY_DATA_ACTION = 'UPDATE_HISTORY_DATA';
export const REMOVE_FROM_CURRENCY_LIST_ACTION = 'REMOVE_FROM_CURRENCY_LIST';
export const RESULTS_UPDATED_ACTION = 'RESULTS_UPDATED';
